version: '3.8'

services:
  postgres:
    image: postgres:13
    environment:
      POSTGRES_USER: airflow
      POSTGRES_PASSWORD: airflow
      POSTGRES_DB: airflow
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - airflow

  airflow:
    build: .
    depends_on:
      - postgres
    environment:
      AIRFLOW__CORE__EXECUTOR: LocalExecutor
      AIRFLOW__CORE__SQL_ALCHEMY_CONN: postgresql+psycopg2://airflow:airflow@postgres/airflow
      AIRFLOW__CORE__LOAD_EXAMPLES: 'false'
      AIRFLOW__WEBSERVER__RBAC: 'true'
      AIRFLOW__WEBSERVER__SECRET_KEY: 'mysecretkey'
      AIRFLOW__CORE_SIMPLE_AUTH_MANAGER_USERS : "bob:admin,peter:viewer"
    volumes:
      - ./dags:/opt/airflow/dags
      - ./logs:/opt/airflow/logs
    ports:
      - "8080:8080"
    entrypoint: /bin/bash -c "
      if [ -s /requirements.txt ]; then pip install --no-cache-dir -r /requirements.txt; fi && \
      airflow db migrate && \
      airflow standalone
      "
    command: >
      bash -c "airflow scheduler & airflow webserver"
    user: airflow
    networks:
      - airflow

volumes:
  postgres_data:

networks:
  airflow:
    driver: bridge
